import {ITicket} from "../models/ITicket";

export const mockdata_tickets: ITicket[] = [
    {
        id: "TKT-001",
        title: "Server Down",
        type: "Technical",
        status: "Open",
        assignedAdmin: "John Doe",
        createdDate: "2023-05-01",
        createdUserMail: "erika.musterfrau@example.com",
        description: "Main server is not responding to requests.",
    },
    {
        id: "TKT-002",
        title: "New Feature Request",
        type: "General",
        status: "In Progress",
        assignedAdmin: "Jane Smith",
        createdDate: "2023-05-02",
        createdUserMail: "erika.musterfrau@example.com",
        description: "Client requested a new reporting feature.",
    },
    {
        id: "TKT-003",
        title: "User Access Issue",
        type: "Organizational",
        status: "Resolved",
        assignedAdmin: "Mike Johnson",
        createdDate: "2023-05-03",
        createdUserMail: "erika.musterfrau@example.com",
        description: "User cannot access their account after password reset.",
    },
    {
        id: "TKT-004",
        title: "Database Performance",
        type: "Technical",
        status: "Open",
        assignedAdmin: "John Doe",
        createdDate: "2023-05-04",
        createdUserMail: "john.doe@example.com",
        description: "Database queries are taking too long to execute.",
    },
    {
        id: "TKT-005",
        title: "UI Redesign Feedback",
        type: "General",
        status: "In Progress",
        assignedAdmin: "Jane Smith",
        createdDate: "2023-05-05",
        createdUserMail: "john.doe@example.com",
        description: "Collecting feedback on the new UI design.",
    },
];
